version: '3.7'

services:
  node:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet

  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_USER: sveta
      MYSQL_PASSWORD: '12345678'
      MYSQL_DATABASE: cafe
    ports:
      - '3306:3306'
    networks:
      - webnet

networks:
  webnet:
volumes:
  mysql-data: {}
