version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - webnet
    command: npm run start:dev

  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_USER: 'sveta'
      MYSQL_PASSWORD: '12345678'
      MYSQL_DATABASE: 'cafe'
    ports:
      - '3309:3306'
    networks:
      - webnet

networks:
  webnet:
volumes:
  mysql-data: { }

